sudo: required
services:
    - docker

before_install:
    - docker-compose build
    # - docker build -t gyans/docker_practice -f Dockerfile.dev .  
    # above not supported due to react-scripts 3.41

script:
    - docker run gyans/docker_practice npm run test -- --coverage